name: Build and Run Tomcat

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build WAR with Maven
        run: mvn -B -DskipTests clean package

      - name: Build Docker image
        run: docker build -t simple-tomcat .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name simple-tomcat simple-tomcat
          sleep 10
          # چک کردن اینکه کانتینر بالا آمده
          curl -f http://localhost:8080/ || (docker ps -a && docker logs simple-tomcat && exit 1)
# Trigger GitHub Actions workflow
