name: Build and Deploy WebLogic App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build WAR with Maven
        run: mvn clean package

      - name: Log in to Oracle Container Registry
        env:
          ORACLE_USER: ${{ secrets.ORACLE_USER }}
          ORACLE_PASS: ${{ secrets.ORACLE_PASS }}
        run: |
          echo "$ORACLE_PASS" | docker login container-registry.oracle.com -u "$ORACLE_USER" --password-stdin

      - name: Build WebLogic Docker image
        run: docker build -t weblogic-app .

      - name: Run WebLogic container (for test)
        run: |
          docker run -d --name weblogic-app -p 7001:7001 weblogic-app
          sleep 60
          docker ps -a
