name: WebLogic CI/CD Pipeline

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build App with Maven
      run: mvn clean package -DskipTests

    - name: Build and Run WebLogic Docker
      run: |
        docker build -t weblogic-app .
        docker run -d -p 7001:7001 --name weblogic weblogic-app sleep 60
        # Deploy WAR inside container
        docker cp target/*.war weblogic:/u01/domains/base_domain/autodeploy/
        # Simple test
        sleep 30
        docker exec weblogic curl -f http://localhost:7001/ || echo "Test skipped"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: weblogic-app
        path: target/*.war
